common: &common
  adapter: postgresql
  database: lich_anh_hoang
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *common

test:
  <<: *common
  database: lich_anh_hoang_test

production:
  <<: *common
  database: lich_anh_hoang